drop table equipment;
drop table transportationtolocation;
drop table retailerfeaturesgear;
drop table userhikestrail;
drop table transportation;
drop table retailer2;
drop table retailer1;
drop table preview2;
drop table preview1;
drop table gear;
drop table review;
drop table photo;
drop table friends;
drop table ugc;
drop table trail;
drop table location;
drop table userprofile;
drop sequence user_id_seq;

-- select 'drop table '||table_name||' cascade constraints;' from user_tables;