DROP TABLE equipment;
DROP TABLE transportationtolocation;
DROP TABLE retailerfeaturesgear;
DROP TABLE userhikestrail;
DROP TABLE transportation;
DROP TABLE retailer2;
DROP TABLE retailer1;
DROP TABLE preview2;
DROP TABLE preview1;
DROP TABLE gear;
DROP TABLE review;
DROP TABLE photo;
DROP TABLE friends;
DROP TABLE ugc;
DROP TABLE trail;
DROP TABLE location;
DROP TABLE userprofile;
DROP SEQUENCE user_id_seq;

-- select 'drop table '||table_name||' cascade constraints;' from user_tables;